### ISSUE TITLE
Upgrade dependency to latest version of spring and spring hateoas

### ISSUE THREAD

**Issue by datenbrille** [BlackPepperSoftware/bowman#1]
Hello,

we are currently using Spring Boot 1.5.4 in our project and would like to use this awesome library. So fare it worked perfectly fine. Are there any plans to upgrade the dependencies to the latest versions?

Best Karl

**Comment by hdpe** [comment]
Hi and thanks for your feedback!

I've updated the library to use dependencies from the latest Spring Boot release (1.5.6).
