### ISSUE TITLE
Java 8 support

### ISSUE THREAD

**Issue by datenbrille** [BlackPepperSoftware/bowman#13]
Hello,

this not real requirement, more like a start of discussion. What do you think about dropping the support of older Java versions and increase the source level to 1.8?

Best Karl

**Comment by hdpe** [comment]
I don't have a problem with it. I know some people are stuck on Java 7, but they're welcome to use previous versions of the library! :)

Spring Boot 2 must be fairly imminent now, and that will drop Java 7 support. There will certainly be no need to support Java 7 once we've switched to Spring Boot 2 to manage our dependencies.

**Comment by datenbrille** [comment]
Shall I create a PR and change the code to Java 8 style, aka lamda etc?

**Comment by hdpe** [comment]
Sure, please do.

We don't need to do everything all at once - there's no need to change every single for loop to a Stream operation or null check to an Optional for example. But if there's anywhere where Java 8 language features improve readability then please feel free to use them!

Thanks
