### ISSUE TITLE
LinkedResource not supporting setting null as valid value

### ISSUE THREAD

**Issue by danieltalebi** [BlackPepperSoftware/bowman#30]
Hi all,

We're using Bowman with the following scenario:

* An Object A that has a nullable LinkedResource Object B (both projects UI and backend)
* Having an instance of A that has a not null instance of B, when setting a.setB(null) it invokes the LinkedResourceMethodHandler.invokeSetterMethod, which sets the value to null (so far so good)
* When a.getB() is invoked, it will invoke LinkedResourceMethodHandler.invokeAnnotatedMethod, which fetches the value again from the backend because the LinkedResource (B) is null. 
* So, we can't set the LinkedResource to null.

We think the correct behaviour should be that if you have set a LinkedResource to null, it shouldn't be overridden by a fetch when you invoke the getter.

Thanks!

**Comment by hdpe** [comment]
Hi @danieltalebi, just to let you know your issue is resolved (hopefully) in release 0.6.1.

Thanks

**Comment by danieltalebi** [comment]
Awesome!!!, I'll give it a try
Cheers
