### ISSUE TITLE
LinkedResource throws "wrong number of arguments" exception

### ISSUE THREAD

**Issue by karolispilypaitis** [BlackPepperSoftware/bowman#31]
When accessing @LinkedResource with parameters (like findAllByName(String name)) throws "wrong number of arguments" exception.
This occurs only when return type is Collection implementation. With single objects it works fine. Also Collections work fine when they are marked with @LinkedResource but have no parameters

**Comment by hdpe** [comment]
Hi, I can't reproduce this - and we have a [test](https://github.com/BlackPepperSoftware/bowman/blob/f630a2cb148690227289b711f9780fbf2b5cabad/test/it/src/test/java/uk/co/blackpepper/bowman/test/it/SimpleEntitySearchIT.java#L55) to verify this works. The test has the following annotated model method:

```
	@LinkedResource
	List<SimpleEntity> findByNameContaining(String query);
```

If you're still having trouble, perhaps you could post some more details (your annotated model class, your client code, and the exception stacktrace?)

Thanks

**Comment by karolispilypaitis** [comment]
OK. Looked into your test code. I had SearchEntity as a class in my model. Changed it to interface and it works.
Thanks! And props to you for this library it is absolutely fantastic. Using it extensively.

**Comment by hdpe** [comment]
That's great - and thanks! I'm thrilled people are using it and finding it useful.
