### ISSUE TITLE
How to use with mockMvc

### ISSUE THREAD

**Issue by ignaciolarranaga** [BlackPepperSoftware/bowman#35]
Do you have some reference at hand ?

**Comment by hdpe** [comment]
Sorry, no, not currently. I've never attempted this.

Could you please describe what you're trying to do? Are you wanting to write some sort of Bowman-aware `RequestPostProcessor` / `ResultMatcher`?

**Comment by ignaciolarranaga** [comment]
I'm writing ITs for some of the business rules of the API, but I solved it more easily that I expected actually, I just write the test as if were a regular client getting the random por from the environment context, e.g:

```
@Test
public void aUserCanNotUpdateTheListingOfAnother() throws Exception {
    String sampleNewTitle = "Other";
    ClientFactory adminUserClientFactory = buildClientFactoryFor(of(obtainAccessToken(ADMIN_DEVICE_ID, ADMIN_DEVICE_SECRET)));
    Client<ListingDto> adminUserListings = adminUserClientFactory.create(ListingDto.class);
    URI uri = adminUserListings.post(sampleListing(null));
    ClientFactory defaultUserClientFactory = buildClientFactoryFor(of(obtainAccessToken(DEFAULT_DEVICE_ID, DEFAULT_DEVICE_SECRET)));
    Client<ListingDto> defaultUserListings = defaultUserClientFactory.create(ListingDto.class);
    exceptionRule.expect(Forbidden.class);

    defaultUserListings.patch(uri, ListingDto.builder().title(sampleNewTitle).build());
}
```

One minor comment, the default ObjectMapper includes the nulls which is not compatible with the PATCH (i.e. tries to clear all fields). I override it as you suggested but it is a little tricky and may be better to suggest to use a Map instead (not sure, just thinking at loud).
