### ISSUE TITLE
Open internal ObjectMapper or Customizer to add additional Modules

### ISSUE THREAD

**Issue by datenbrille** [BlackPepperSoftware/bowman#6]
This is something more specific for Java 8 and the new Time API within Java 8. To support serialisation and deserialisation of `LocalDateTime` and `ZonedLocatDate` it is necessary to register additional modules to the Jackson ObjectMapper.

I suggest the same approach as for the `ClientFactory` and `RestTemplateCustomizer`. Enhance the `Configuration` class and pass an external `ObjectMapper` or even better a customizer to the underlying system. The default would be the current `DefaultObjectMapperFactory`.

What do you think?

**Comment by hdpe** [comment]
This sounds good to me - I think the most in keeping approach would be to define an `ObjectMapperConfigurer` (analagous to the existing `RestTemplateConfigurer`) and invoke this if present in `RestOperationsInstantiation` in the same way.

Feel free to make a PR!

Thanks

**Comment by datenbrille** [comment]
Ok, I will start working on this.

**Comment by hdpe** [comment]
Fixed by #9 - thanks very much @datenbrille !
